version: "v1"
CRA_TARGETS:
  - CRA_TARGET: "examples/fscloud"
    CRA_IGNORE_RULES_FILE: "cra-tf-validate-ignore-rules.json"
    PROFILE_ID: "fe96bd4d-9b37-40f2-b39f-a62760e326a3" # SCC profile ID (currently set to 'IBM Cloud Framework for Financial Services' '1.7.0' profile).
    CRA_ENVIRONMENT_VARIABLES:  # An optional map of environment variables for CRA, where the key is the variable name and value is the value. Useful for providing TF_VARs.
      TF_VAR_hpcs_instance_guid: "e6dce284-e80f-46e1-a3c1-830f7adff7a9"
      TF_VAR_hpcs_key_crn_cluster: "crn:v1:bluemix:public:hs-crypto:us-south:a/abac0df06b644a9cabc6e44f55b3880e:e6dce284-e80f-46e1-a3c1-830f7adff7a9:key:1368d2eb-3ed0-4a8b-b09c-2155895f01ea"
      TF_VAR_hpcs_key_crn_worker_pool: "crn:v1:bluemix:public:hs-crypto:us-south:a/abac0df06b644a9cabc6e44f55b3880e:e6dce284-e80f-46e1-a3c1-830f7adff7a9:key:1368d2eb-3ed0-4a8b-b09c-2155895f01ea"
      TF_VAR_region: "us-south"
      TF_VAR_prefix: "base-ocp-std"
